#!/bin/bash


####################################################################################################
#
#                           █████╗ ██████╗  ██████╗██╗  ██╗    ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗
#                          ██╔══██╗██╔══██╗██╔════╝██║  ██║    ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝
#                          ███████║██████╔╝██║     ███████║    ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝
#                          ██╔══██║██╔══██╗██║     ██╔══██║    ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗
#                          ██║  ██║██║  ██║╚██████╗██║  ██║    ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗
#                          ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝    ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝
#   ███████╗██╗███╗   ███╗██████╗ ██╗     ███████╗    ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗
#   ██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝    ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
#   ███████╗██║██╔████╔██║██████╔╝██║     █████╗      ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
#   ╚════██║██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝      ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
#   ███████║██║██║ ╚═╝ ██║██║     ███████╗███████╗    ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
#   ╚══════╝╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝    ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# Author: fluffeh
# v2.0 - 26-01-2021
# Source: https://git.io/fluffeh-archsin
# Details: This is the barebones install. It will leave you with a working system.
#   For quick program installation and configuration use archsin-pinstall
#
####################################################################################################

#exiting if any error encountered
set -e;

#keep track of the last executed command
trap 'lastCommand=$currentCommand; currentCommand=$BASH_COMMAND' DEBUG;
#print error message before exitting
trap 'echo "\"${lastCommand}\" command failed with exit code $?."' EXIT;


# Pulling functions file
curl --remote-name "https://raw.githubusercontent.com/fluffehGit/archsin/master/archsin-functions";
source archsin-functions;

## Installation sequence

#Checking BIOS type
systemCheck;

# Updating the system clock
timedatectl set-ntp true;

# Env setup
getEnvironment;

# Setting mirrorlist
setMirrors;

# Parttion disk
setDisk;

# Installing essentials
pacstrap /mnt base base-devel linux linux-firmware linux-headers btrfs-progs grub grub-btrfs efibootmgr networkmanager network-manager-applet bc vim git openssh;

# Generating FSTab
genfstab -U /mnt >> /mnt/etc/fstab;

cp archsin-functions /mnt/root/;

arch-chroot /mnt /bin/bash -- << EOCHROOT

    source \$HOME/archsin-functions;

    createSwap;
    setLocale "${CITY}";
    setHost "${HSTNAME}";
    setInitramfs "${REPOAPITOKEN}" "${REPOID}";
    setUser "${USRGROUPS}" "${USRNAME}" "${USRPASSWD}" "${REPOAPITOKEN}" "${REPOID}";

    systemctl enable NetworkManager.service

EOCHROOT


shred --verbose -u --zero --iterations=3 /mnt/root/archsin-functions;

<<blockComment
sed --in-place \
    "s/#PLACEHOLDER/\
    REPOAPITOKEN=\"${REPOAPITOKEN}\"\n\
    REPOID=\"${REPOID}\"\n\
    GITUSR=\"${GITUSR}\"\n\
    GITMAIL=\"${GITMAIL}\"\n\
    GITROOTUSR=\"${GITROOTUSR}\"\n\
    GITROOTMAIL=\"${GITROOTMAIL}\"\n\
    HSTNAME=\"${HSTNAME}\"\n/" \
    /mnt/home/$USRNAME/archsin-pinstall;
blockComment
