#!/bin/bash

########################################
#
#                           █████╗ ██████╗  ██████╗██╗  ██╗    ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗
#                          ██╔══██╗██╔══██╗██╔════╝██║  ██║    ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝
#                          ███████║██████╔╝██║     ███████║    ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝
#                          ██╔══██║██╔══██╗██║     ██╔══██║    ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗
#                          ██║  ██║██║  ██║╚██████╗██║  ██║    ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗
#                          ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝    ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝
#   ███████╗██╗███╗   ███╗██████╗ ██╗     ███████╗    ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗
#   ██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝    ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
#   ███████╗██║██╔████╔██║██████╔╝██║     █████╗      ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
#   ╚════██║██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝      ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
#   ███████║██║██║ ╚═╝ ██║██║     ███████╗███████╗    ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
#   ╚══════╝╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝    ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# Author: fluffeh
# v1.0 - 26.12.2020
# Source: https://git.io/fluffeh-archsin
# Install command: curl --location "https://git.io/fluffeh-archsin" --output ./archsin
#
########################################

# Pulling Disk Layout file
curl "https://raw.githubusercontent.com/fluffehGit/archsin/master/efiBTRFS.disk.layout" --output ./efiBTRFS.disk.layout

# Pulling functions file
curl "https://raw.githubusercontent.com/fluffehGit/archsin/master/functions" --output ./functions;
source functions

## Installation sequence
systemCheck;

# Updating the system clock
timedatectl set-ntp true && \
    # Env setup
    getEnvironment;

# Installing essentials
pacstrap /mnt base base-devel linux linux-firmware linux-headers;

# Generating FSTab
genfstab -U /mnt >> /mnt/etc/fstab;

arch-chroot /mnt /bin/bash -x chrooted;

# TO DO
echo "SET UP GIT USER:";
echo "git config --global user.name 'username'";
echo "git config --global user.email 'email'";
echo "git config --global --list";
echo "Generate ssh keys and add them to GitHub and GitLab!!!";
echo "ssh-keygen -t ed25519 -C 'user+machine'";
echo "cat ~/.ssh/id_ed25519.pub | xclip -selection clipboard";
echo "TEST WITH ssh -T git@git{hub,lab}.com";
echo "ADD GIT REMOTE TO etckeeper!!!";
# Exiting chroot
#exit;

#umount -a;

#reboot;
