#!/bin/bash

########################################
#
#                           █████╗ ██████╗  ██████╗██╗  ██╗    ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗
#                          ██╔══██╗██╔══██╗██╔════╝██║  ██║    ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝
#                          ███████║██████╔╝██║     ███████║    ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝
#                          ██╔══██║██╔══██╗██║     ██╔══██║    ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗
#                          ██║  ██║██║  ██║╚██████╗██║  ██║    ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗
#                          ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝    ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝
#   ███████╗██╗███╗   ███╗██████╗ ██╗     ███████╗    ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗
#   ██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝    ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
#   ███████╗██║██╔████╔██║██████╔╝██║     █████╗      ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
#   ╚════██║██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝      ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
#   ███████║██║██║ ╚═╝ ██║██║     ███████╗███████╗    ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
#   ╚══════╝╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝    ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
# Author: fluffeh
# v1.0 - 26.12.2020
# Source: https://git.io/fluffeh-archsin
# Install command: curl --location "https://git.io/fluffeh-archsin" --output ./archsin && chmod 744 archsin
#
########################################

# Pulling Disk Layout file
curl "https://raw.githubusercontent.com/fluffehGit/archsin/master/efiBTRFS.disk.layout" --output ./efiBTRFS.disk.layout

# Pulling functions file
curl "https://raw.githubusercontent.com/fluffehGit/archsin/master/functions" --output ./functions;
source functions

## Installation sequence
systemCheck;

# Updating the system clock
timedatectl set-ntp true;

# Env setup
getEnvironment;

# Setting mirrorlist
setMirrors;

# Parttion disk
setDisk;

# Installing essentials
pacstrap /mnt base base-devel linux linux-firmware linux-headers btrfs-progs snapper grub grub-btrfs efibootmgr;

# Generating FSTab
genfstab -U /mnt >> /mnt/etc/fstab;

: << 'EOBCOMM'
# Executed as user in chroot environment
function executeAsUser {

    setYay;

    setAURPkgs;

    setGit $GITUSR $GITMAIL;

    setDotfiles;

}

# Executed as root in chroot environment
function chrooted {

    createSwap;

    installPackages;

    setLocale;

    setHost;

    ramDiskEnvGrub;

    setUser;

    # Executing User function
    sudo --user=$USRNAME --login executeAsUser;

    setSnapper;

    # Pulling configs
    getConfigs;

    setGit $GITROOTUSR $GITROOTMAIL;

    # Finishing touches
    setApps;

    # Enabling services
    systemctl enable NetworkManager;
    systemctl enable bluetooth;
    systemctl enable tlp.service
}

EOBCOMM

cp functions /mnt/root/;

arch-chroot /mnt /bin/bash << EOCHROOT

    source \$HOME/functions;

    createSwap;
    installPackages $GITLABHEADER $REPOID;
    setLocale $CITY;
    setHost $HSTNAME;
    ramDiskEnvGrub $GITLABHEADER $REPOID;
    setUser $USRGROUPS $USRNAME;

    cp \$HOME/functions /home/$USRNAME/functions

    sudo --user=$USRNAME --login /bin/bash <<-EOUSER

        source \$HOME/functions;

        setYay;
        setAURPkgs $GITLABHEADER $REPOID;
        setGit $GITUSR $GITMAIL $HSTNAME;
        setDotFiles;

	EOUSER

    rm /home/$USRNAME/functions

    setSnapper $GITLABHEADER $REPOID;
    getConfigs $GITLABHEADER $REPOID;
    setGit $GITROOTUSR $GITROOTMAIL $HSTNAME;
    setApps $GITLABHEADER $REPOID;

    systemctl enable NetworkManager;
    systemctl enable bluetooth;
    systemctl enable tlp.service;

EOCHROOT

rm /mnt/root/functions

# Remaining TO-DOs
echo "cat ~/.ssh/id_ed25519.pub | xclip -selection clipboard";
echo "TEST WITH ssh -T git@git{hub,lab}.com";
echo "ADD GIT REMOTES!!!";
