#!/bin/bash

function setYay {

    mkdir --parents $HOME/AUR/yay;
    git clone https://aur.archlinux.org/yay.git $HOME/AUR/yay;
    cd $HOME/AUR/yay;
    makepkg --syncdeps --install --rmdeps --clean --noconfirm;
    cd $HOME;

}

function setAURPkgs {

    curl --header "${1}" "https://gitlab.com/api/v4/projects/${$2}/repository/files/pacman.aurpkgs.list/raw?ref=master" --output $HOME/aur.pkgs.list;
    yay -Syy --needed --nodiffmenu --answerclean All --removemake --cleanafter - < $HOME/aur.pkgs.list --noconfirm;
    rm --force $HOME/aur.pkgs.list;
}

function setSnapper {

    # Snapper setup
    # Below two lines needed bc snapper create-config creates .snapshots folder
    umount --force /.snapshots;
    rm --recursive --force /.snapshots;

    snapper --config root create-config /;

    curl --header "${1}" "https://gitlab.com/api/v4/projects/${2}/repository/files/snapper%2Fconfigs%2Froot/raw?ref=master" --output /etc/snapper/configs/root;

    chmod 755 /.snapshots;
    systemctl enable snapper-timeline.timer;
    systemctl enable snapper-cleanup.timer;
    systemctl enable grub-btrfs.path

}

function setApps {

    # ClamAV setup
    freshclam;
    systemctl enable clamav-freshclam.service;

    # Fangfrisch database
    sudo --user=clamav /usr/bin/fangfrisch --conf /etc/fangfrisch/fangfrisch.conf initdb;
    systemctl enable fangfrisch.timer;

    # etckeeper
    etckeeper init;
    etckeeper commit "fresh install";
    systemctl enable etckeeper.timer;

    # rkhunter
    rkhunter --propupd;
    curl --header "${1}" "https://gitlab.com/api/v4/projects/${2}/repository/files/systemd%2Fsystem%2Frkhunter.timer/raw?ref=master" --output /etc/sytemd/system/rkhunter.timer;
    systemctl enable rkhunter.timer.

    systemctl enable NetworkManager;
    systemctl enable bluetooth;
    systemctl enable tlp.service;

}

# Git Setup
git config --global user.name $GITUSR;
git config --global user.email $GITMAIL;

# Generating ED25519 keyfile
ssh-keygen -t ed25519 -C "${USER} on ${HSTNAME}";

setYay;
setAURPkgs "${GITLABHEADER}" "${REPOID}";
setGit "${GITUSR}" "${GITMAIL}" "${HSTNAME}";
sudo setSnapper "${GITLABHEADER}" "${REPOID}";
sudo setApps "${GITLABHEADER}" "${REPOID}";

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;

# Remaining TO-DOs
echo "cat ~/.ssh/id_ed25519.pub | xclip -selection clipboard";
echo "TEST WITH ssh -T git@git{hub,lab}.com";
echo "ADD GIT REMOTES!!!";
echo "ADD root passwd!!!";

#rm -rf ./post-install
