#!/bin/bash

function setYay {

    mkdir --parents $HOME/AUR/yay;
    git clone https://aur.archlinux.org/yay.git $HOME/AUR/yay;
    cd $HOME/AUR/yay;
    makepkg --syncdeps --install --rmdeps --clean --noconfirm;
    cd $HOME;

}

function setAURPkgs {

    curl --header "${1}" "https://gitlab.com/api/v4/projects/${$2}/repository/files/pacman.aurpkgs.list/raw?ref=master" --output $HOME/aur.pkgs.list;
    yay -Syy --needed --nodiffmenu --answerclean All --removemake --cleanafter - < $HOME/aur.pkgs.list --noconfirm;
    rm --force $HOME/aur.pkgs.list;
}

function setGit {

    # Git Setup
    git config --global user.name $1;
    git config --global user.email $2;

    # Generating ED25519 keyfile
    ssh-keygen -t ed25519 -C "${USER} on ${3}";

}

function setSnapper {

    # Snapper setup
    # Below two lines needed bc snapper create-config creates .snapshots folder
    umount --force /.snapshots;
    rm --recursive --force /.snapshots;

    snapper --config root create-config /;

    curl --header "${1}" "https://gitlab.com/api/v4/projects/${2}/repository/files/snapper%2Fconfigs%2Froot/raw?ref=master" --output /etc/snapper/configs/root;

    chmod 755 /.snapshots;
    systemctl enable snapper-timeline.timer;
    systemctl enable snapper-cleanup.timer;
    systemctl enable grub-btrfs.path

}

if [[ -f gitlabAPIRead.token ]]; then
    read GITLABHEADER < gitlabAPIRead.token;
else
    read -p "Input GitLab API token: " GITLABHEADER;
fi

GITLABHEADER="PRIVATE-TOKEN: "$GITLABHEADER;

if [[ -f gitlabEtcRepo.ID ]]; then
    read REPOID < gitlabEtcRepo.ID;
else
    read -p "Input GitLab /etc repo ID: " REPOID;
fi

setYay;
setAURPkgs "${GITLABHEADER}" "${REPOID}";
setGit "${GITUSR}" "${GITMAIL}" "${HSTNAME}";
setSnapper "${GITLABHEADER}" "${REPOID}";

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim;

# Remaining TO-DOs
echo "cat ~/.ssh/id_ed25519.pub | xclip -selection clipboard";
echo "TEST WITH ssh -T git@git{hub,lab}.com";
echo "ADD GIT REMOTES!!!";
echo "ADD root passwd!!!";

#rm -rf ./post-install
